<a href="https://colab.research.google.com/github/juhumkwon/source_code/blob/main/2_1%EA%B0%95_%EB%B0%B0%EC%97%B4%2C_%EB%A6%AC%EC%8A%A4%ED%8A%B8%2C_matrix%2C_slice%2C_reshape_%EB%93%B1_%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#리스트 (List) 사용 예
#리스트는 다양한 데이터 타입을 하나의 컬렉션에 저장할 수 있습니다.

my_list = [1, "hello", 3.14, True, [1, 2, 3]]
print(my_list)
# 출력: [1, 'hello', 3.14, True, [1, 2, 3]]

[1, 'hello', 3.14, True, [1, 2, 3]]


In [ ]:
#요소 추가 및 삭제
my_list = [1, 2, 3]
my_list.append(4)  # 요소 추가
print(my_list)  # 출력: [1, 2, 3, 4]

my_list.remove(2)  # 요소 삭제
print(my_list)  # 출력: [1, 3, 4]

[1, 2, 3, 4]
[1, 3, 4]


In [ ]:
#슬라이싱 (Slicing)
my_list = [1, 2, 3, 4, 5, 6]
sliced_list = my_list[1:4]  # 인덱스 1부터 3까지
print(sliced_list)  # 출력: [2, 3, 4]

[2, 3, 4]


In [ ]:
#중첩 리스트

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matrix[1][2])  # 출력: 6 (2번째 행, 3번째 열)


6


In [ ]:
#배열 (Array) 사용 예
#배열은 모든 요소가 동일한 데이터 타입을 가져야 하므로, 효율적으로 메모리를 사용할 수 있습니다.

import array
import numpy as np # Import the NumPy library

my_array = array.array('i', [1, 2, 3, 4, 5])
print(my_array)
# 출력: array('i', [1, 2, 3, 4, 5])

# Convert the array.array object to a NumPy array
numpy_array = np.array(my_array)

print(numpy_array.shape) # Now you can access the shape attribute

array('i', [1, 2, 3, 4, 5])
(5,)


In [ ]:
#과학 계산에서의 NumPy 배열 사용
#NumPy 배열은 대규모 데이터 계산에서 매우 유용합니다. 다차원 배열을 쉽게 다룰 수 있습니다.

import numpy as np

# 2차원 배열 (행렬) 생성
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#요소별 연산

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

d = [7, 8, 9]
e = [10,11,12]

# 요소별 덧셈
c = a + b
print(c)

f = d + e
print(f)

[5 7 9]
[7, 8, 9, 10, 11, 12]


In [ ]:
"""
슬라이싱(slicing)은 파이썬에서 리스트, 튜플, 문자열,
배열 등의 데이터 구조에서 특정 부분을 선택하여 가져오는 방법입니다.
슬라이싱은 기본적으로 start:stop:step 형식으로 사용됩니다.

여기서:
start: 슬라이스의 시작 인덱스 (포함됨).
stop: 슬라이스의 종료 인덱스 (포함되지 않음).
step: 슬라이스의 간격 (기본값은 1).
"""
my_list = [10, 20, 30, 40, 50]

# 인덱스 1부터 3까지 (3은 포함되지 않음)
sliced_list = my_list[1:3]
print(sliced_list)  # 출력: [20, 30]


[20, 30]


In [ ]:
#시작 인덱스와 종료 인덱스 생략

# 시작 인덱스를 생략 (0부터 시작)
sliced_list = my_list[:3]
print(sliced_list)  # 출력: [10, 20, 30]

# 종료 인덱스를 생략 (끝까지)
sliced_list = my_list[2:]
print(sliced_list)  # 출력: [30, 40, 50]

# 시작과 종료 인덱스를 모두 생략 (전체 리스트)
sliced_list = my_list[:]
print(sliced_list)  # 출력: [10, 20, 30, 40, 50]


[10, 20, 30]
[30, 40, 50]
[10, 20, 30, 40, 50]


In [ ]:
#음수 인덱스를 사용한 슬라이싱

# 마지막 두 요소 슬라이싱
sliced_list = my_list[-2:]
print(sliced_list)  # 출력: [40, 50]

# 처음부터 마지막 두 요소를 제외한 나머지 슬라이싱
sliced_list = my_list[:-2]
print(sliced_list)  # 출력: [10, 20, 30]


[40, 50]
[10, 20, 30]


In [ ]:
#스텝(step) 사용

# 리스트의 모든 요소를 2씩 건너뛰며 슬라이싱
sliced_list = my_list[::2]
print(sliced_list)  # 출력: [10, 30, 50]

# 리스트를 역순으로 슬라이싱
sliced_list = my_list[::-1]
print(sliced_list)  # 출력: [50, 40, 30, 20, 10]



[10, 30, 50]
[50, 40, 30, 20, 10]
Hello


In [ ]:
my_string = "Hello, World!"

# 인덱스 0부터 4까지 슬라이싱
sliced_string = my_string[0:5]
print(sliced_string)  # 출력: "Hello"

# 문자열의 모든 문자를 2씩 건너뛰며 슬라이싱
sliced_string = my_string[::2]
print(sliced_string)  # 출력: "Hlo ol!"

# 문자열을 역순으로 슬라이싱
sliced_string = my_string[::-1]
print(sliced_string)  # 출력: "!dlroW ,olleH"

Hello
Hlo ol!
!dlroW ,olleH


In [51]:
#다차원 배열의 슬라이싱
#NumPy 배열(NumPy Array) 슬라이싱

import numpy as np

# 2차원 배열 생성
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 첫 두 행과 첫 두 열을 슬라이싱
sliced_array = array[:2, :2]
print(sliced_array)
# 출력:
# [[1 2]
#  [4 5]]

# 첫 번째 행 전체를 슬라이싱
sliced_array = array[0, :]
print(sliced_array)  # 출력: [1 2 3]

# 첫 번째 열 전체를 슬라이싱
sliced_array = array[:, 0]
print(sliced_array)  # 출력: [1 4 7]

# 배열을 역순으로 슬라이싱
sliced_array = array[::-1, ::-1]
print(sliced_array)
# 출력:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

[[1 2]
 [4 5]]
[1 2 3]
[1 4 7]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [53]:
# 3차원 배열 생성
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

# 첫 번째 차원의 첫 번째 요소를 슬라이싱
sliced_tensor = tensor[0]
print(sliced_tensor)
# 출력:
# [[1 2]
#  [3 4]]

# 모든 차원에서 첫 번째 요소만을 슬라이싱
sliced_tensor = tensor[:, 0, 0]
print(sliced_tensor)  # 출력: [1 5 9]

# 모든 차원에서 역순으로 슬라이싱
sliced_tensor = tensor[::-1, ::-1, ::-1]
print(sliced_tensor)
# 출력:
# [[[12 11]
#   [10  9]]
#
#  [[ 8  7]
#   [ 6  5]]
#
#  [[ 4  3]
#   [ 2  1]]]

[[1 2]
 [3 4]]
[1 5 9]
[[[12 11]
  [10  9]]

 [[ 8  7]
  [ 6  5]]

 [[ 4  3]
  [ 2  1]]]


In [ ]:
#배열의 크기 및 형태 변경
#NumPy는 배열의 형태를 쉽게 변경할 수 있는 기능을 제공합니다.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # 2x3 배열로 재구성
print(reshaped_arr)

print("\n")
print(arr.shape)
print(reshaped_arr.shape)


[[1 2 3]
 [4 5 6]]


(6,)
(2, 3)


In [ ]:
#NumPy 배열에서의 shape

import numpy as np

# 2x3 배열 생성
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 배열의 shape 확인
print(matrix.shape)
# 출력: (2, 3)

(2, 3)


In [ ]:
#다차원 배열에서의 shape

import numpy as np

# 2x3x4 배열 생성
tensor = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

# 배열의 shape 확인
print(tensor.shape)
# 출력: (2, 3, 4)

(2, 3, 4)


In [ ]:
"""
axis는 NumPy에서 다차원 배열의 연산 방향을 지정하는 데 사용되는 개념입니다.
간단히 말해, 배열에서 어떤 차원(축)을 따라 연산을 수행할지를 지정하는 것입니다.

기본 개념
축 0 (axis=0): 첫 번째 축으로, 배열의 행 방향을 나타냅니다. 이 축을 따라 연산을 수행하면,
               열을 기준으로 계산이 이루어집니다.
축 1 (axis=1): 두 번째 축으로, 배열의 열 방향을 나타냅니다. 이 축을 따라 연산을 수행하면,
               행을 기준으로 계산이 이루어집니다.
"""

import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

"""
axis=0은 행을 따라 연산을 수행하는 것을 의미합니다.
예를 들어, sum 함수에서 axis=0으로 지정하면 각 열의 합이 계산됩니다.
"""
sum_axis_0 = matrix.sum(axis=0)
print(sum_axis_0)
# 출력: [12 15 18]

"""
axis=1은 열을 따라 연산을 수행하는 것을 의미합니다.
예를 들어, sum 함수에서 axis=1으로 지정하면 각 행의 합이 계산됩니다.
"""
sum_axis_1 = matrix.sum(axis=1)
print(sum_axis_1)
# 출력: [ 6 15 24]

[12 15 18]
[ 6 15 24]


In [ ]:
#예제 2: 3차원 배열에서의 axis
#3차원 배열의 경우 각 차원이 axis=0, axis=1, axis=2로 지정될 수 있습니다.

tensor = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(tensor.shape)

"""
이 배열은 2x2x3 크기를 가지며, 각 차원에 대해 axis를 지정할 수 있습니다.
axis=0: 첫 번째 차원(가장 바깥 차원)을 따라 연산.
axis=1: 두 번째 차원을 따라 연산.
axis=2: 세 번째 차원을 따라 연산.
"""
sum_axis_0 = tensor.sum(axis=0)
print(sum_axis_0)
# 출력:
# [[ 8 10 12]
#  [14 16 18]]
print("\n")

sum_axis_1 = tensor.sum(axis=1)
print(sum_axis_1)
# 출력:
# [[ 5  7  9]
#  [17 19 21]]
print("\n")

sum_axis_2 = tensor.sum(axis=2)
print(sum_axis_2)
# 출력:
# [[ 6 15]
#  [24 33]]


(2, 2, 3)
[[ 8 10 12]
 [14 16 18]]


[[ 5  7  9]
 [17 19 21]]


[[ 6 15]
 [24 33]]
