<a href="https://colab.research.google.com/github/juhumkwon/source_code/blob/main/GradientTape%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# 예제 1
import tensorflow as tf

# 정의할 모델 파라미터
x = tf.Variable(3.0)

# GradientTape을 사용한 연산
with tf.GradientTape() as tape:
    y = x**2  # 단순한 함수 예시: y = x^2

# 그래디언트 계산
dy_dx = tape.gradient(y, x)
print(dy_dx.numpy())  # 출력: 6.0, x=3일 때 y=x^2의 미분값


# 예제 2
import tensorflow as tf

# 모델 파라미터와 입력 데이터
x = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
w = tf.Variable([[0.1, 0.2], [0.3, 0.4]])

with tf.GradientTape() as tape:
    # 모델 연산
    y = tf.matmul(x, w)
    loss = tf.reduce_mean(tf.square(y - [[1.0, 2.0], [3.0, 4.0]]))  # MSE loss
    print("loss=", loss.numpy())

# 그래디언트 계산
dL_dx = tape.gradient(loss, [x, w])
print(dL_dx)

6.0
loss= 1.645
[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.115, -0.245],
       [-0.255, -0.585]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.4      , -3.1999998],
       [-3.3      , -4.6      ]], dtype=float32)>]
