<a href="https://colab.research.google.com/github/juhumkwon/source_code/blob/main/LSTM_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

from numpy import array

from keras.models import Sequential

from keras.layers import Dense, LSTM



# 1. 데이터

x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]])

y = array([4,5,6,7])



print('x shape : ', x.shape) # (4,3)

print('y shape : ', y.shape) # (4,)

#  x  y

# 123 4

# 234 5

# 345 6

# 456 7



print(x)

print('-------x reshape-----------')

x = x.reshape((x.shape[0], x.shape[1], 1)) # (4,3,1) reshape 전체 곱 수 같아야 4*3=4*3*1

print('x shape : ', x.shape)

print(x)

#  x        y

# [1][2][3] 4

# .....



# 2. 모델 구성

model = Sequential()

model.add(LSTM(10, activation = 'relu', input_shape=(3,1)))

# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)

model.add(Dense(5))

model.add(Dense(1))



model.summary()



# 3. 실행

model.compile(optimizer='adam', loss='mse')

model.fit(x, y, epochs=100, batch_size=1)



x_input = array([6,7,8])

x_input = x_input.reshape((1,3,1))



yhat = model.predict(x_input)

print(yhat)

x shape :  (4, 3)
y shape :  (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
-------x reshape-----------
x shape :  (4, 3, 1)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_1 (LSTM)                        │ (None, 10)                  │             480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 5)                   │              55 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               6 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 541 (2.11 KB)

 Trainable params: 541 (2.11 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 26.0130
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.6603 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.4877 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26.8439 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.1485 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.4336 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.1131 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.8586 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.7667 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.9926 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.6831 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.5082 
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.8654 
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.4843 
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.2641 
Epoch